# codecov.yml

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "src/prior_build"
  - "wave.jl"
  - "verify_drp.jl"