## This script builds the skyCont priors from a bunch of samples generated by sample_sky.jl
# Author - Andrew Saydjari, CfA

import Pkg; using Dates; t0 = now(); t_then = t0;
using InteractiveUtils; versioninfo()
Pkg.activate("../../"); Pkg.instantiate(); Pkg.precompile()
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now-t_then)); println("Package activation took $dt"); t_then = t_now; flush(stdout)
using BLISBLAS
using Distributed, SlurmClusterManager, Suppressor, DataFrames
addprocs(SlurmManager(),exeflags=["--project=../../"])
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now-t_then)); println("Worker allocation took $dt"); t_then = t_now; flush(stdout)

@everywhere begin
    using BLISBLAS
    using LinearAlgebra
    BLAS.set_num_threads(1)
    using FITSIO, Serialization, HDF5, LowRankOps, EllipsisNotation, ShiftedArrays
    using Interpolations, SparseArrays, ParallelDataTransfer, AstroTime, Suppressor
    using ThreadPinning

    prior_dir = "/uufs/chpc.utah.edu/common/home/u6039752/scratch1/working/"
    prior_dir0 = "/uufs/chpc.utah.edu/common/home/u6039752/scratch/working/"
    src_dir = "../../"
    include(src_dir*"src/utils.jl")
    include(src_dir*"src/gridSearch.jl")
    include(src_dir*"src/componentAndPosteriors.jl")
    include(src_dir*"src/fileNameHandling.jl")
    include(src_dir*"src/ingest.jl")
    include(src_dir*"src/lowRankPrescription.jl")
    include(src_dir*"src/marginalizeEW.jl")
    include(src_dir*"src/spectraInterpolation.jl")
    include(src_dir*"src/chi2Wrappers.jl")
    include(src_dir*"src/prior_build/prior_utils.jl")
    
    using StatsBase, ProgressMeter
end
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now-t_then)); println("Worker loading took $dt"); t_then = t_now; flush(stdout)

# Task-Affinity CPU Locking in multinode SlurmContext
slurm_cpu_lock()
println(BLAS.get_config()); flush(stdout)
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now-t_then)); println("CPU locking took $dt"); t_then = t_now; flush(stdout)

using LibGit2; git_branch, git_commit = initalize_git(src_dir); @passobj 1 workers() git_branch; @passobj 1 workers() git_commit

@everywhere begin
    runlist_range = 335 #1:600 #295, 245, 335, 101

    nsub = 30; # my star cont is 60... do we need to up it?

    # Prior Dictionary
    prior_dict = Dict{String,String}()

    sky_base = prior_dir*"2024_02_17/apMADGICS.jl/src/prior_build/"

    # Location of the samples
    prior_dict["skycont"] = sky_base*"sky_prior_disk/skycont_"
    prior_dict["skyline"] = sky_base*"sky_prior_disk/skyline_"
    prior_dict["skymsk"] = sky_base*"sky_prior_disk/skymsk_"
    prior_dict["skyvar"] = sky_base*"sky_prior_disk/skyvar_"
    prior_dict["chebmsk_exp"] = sky_base*"sky_prior_disk/chebmsk_exp_"

    prior_dict["skyline_tellDiv"] = sky_base*"sky_prior_disk/skyline_tellDiv_"
    prior_dict["skymsk_tellDiv"] = sky_base*"sky_prior_disk/skymsk_tellDiv_"
    prior_dict["skyvar_tellDiv"] = sky_base*"sky_prior_disk/skyvar_tellDiv_"
end

@everywhere begin
    wavetarg = 10 .^range((4.179-125*6.0e-6),step=6.0e-6,length=8575+125) #first argument is start, revert fix to enable 1.6 compat
    minw, maxw = extrema(wavetarg)
end

@everywhere begin
    function build_skyCont(adjfibindx)
        fname = "sky_priors/APOGEE_skycont_svd_"*string(nsub)*"_f"*lpad(adjfibindx,3,"0")*".h5"
        if !isfile(fname)
            savename = prior_dict["skycont"]*lpad(adjfibindx,3,"0")*".jdat"
            skycont = deserialize(savename)

            savename = prior_dict["skyline"]*lpad(adjfibindx,3,"0")*".jdat"
            skyline = deserialize(savename)

            savename = prior_dict["skymsk"]*lpad(adjfibindx,3,"0")*".jdat"
            skymsk = deserialize(savename);

            savename = prior_dict["skyvar"]*lpad(adjfibindx,3,"0")*".jdat"
            skyvar = deserialize(savename);

            savename = prior_dict["chebmsk_exp"]*lpad(adjfibindx,3,"0")*".jdat"
            chebmsk_exp = deserialize(savename);

            specsum = dropdims(sum(skycont,dims=1),dims=1)
            Vred = skycont[chebmsk_exp,specsum.>0];
            weights = ones(size(Vred,2));
            Vred .*= reshape(weights,1,:);
            nsamp = size(Vred,2)
            norm_weights = weights'*weights
            Csky = Vred*Vred'
            Csky./=norm_weights

            SF = svd(Csky);
            EVEC = zeros(length(wavetarg),size(SF.U,2))
            EVEC[chebmsk_exp,:].=SF.U;

            dirName = splitdir(fname)[1]
            if !ispath(dirName)
                mkpath(dirName)
            end
            h5write(fname,"Vmat",EVEC[:,1:nsub]*Diagonal(sqrt.(SF.S[1:nsub])))
            h5write(fname,"λv",SF.S[1:nsub])
            h5write(fname,"chebmsk_exp",chebmsk_exp)
        end

        # Tell-free sky version for building Tfun/starCont prior
        fname = "sky_priors/APOGEE_skycont_tellDiv_svd_"*string(nsub)*"_f"*lpad(adjfibindx,3,"0")*".h5"
        if !isfile(fname)
            savename = prior_dict["skycont_tellDiv"]*lpad(adjfibindx,3,"0")*".jdat"
            skycont = deserialize(savename)

            savename = prior_dict["skyline_tellDiv"]*lpad(adjfibindx,3,"0")*".jdat"
            skyline = deserialize(savename)

            savename = prior_dict["skymsk_tellDiv"]*lpad(adjfibindx,3,"0")*".jdat"
            skymsk = deserialize(savename);

            savename = prior_dict["skyvar_tellDiv"]*lpad(adjfibindx,3,"0")*".jdat"
            skyvar = deserialize(savename);

            savename = prior_dict["chebmsk_exp"]*lpad(adjfibindx,3,"0")*".jdat"
            chebmsk_exp = deserialize(savename);

            specsum = dropdims(sum(skycont,dims=1),dims=1)
            Vred = skycont[chebmsk_exp,specsum.>0];
            weights = ones(size(Vred,2));
            Vred .*= reshape(weights,1,:);
            nsamp = size(Vred,2)
            norm_weights = weights'*weights
            Csky = Vred*Vred'
            Csky./=norm_weights

            SF = svd(Csky);
            EVEC = zeros(length(wavetarg),size(SF.U,2))
            EVEC[chebmsk_exp,:].=SF.U;

            h5write(fname,"Vmat",EVEC[:,1:nsub]*Diagonal(sqrt.(SF.S[1:nsub])))
            h5write(fname,"λv",SF.S[1:nsub])
            h5write(fname,"chebmsk_exp",chebmsk_exp)
        end
    end
end

BLAS.set_num_threads(64); build_skyCont(runlist_range)
# @showprogress pmap(solve_sky_prior_fiber,1:600) # 13ish hours on 4 np nodes